### ISSUE TITLE
Add logging functionality

### ISSUE THREAD

**Issue by jthomerson** [silvermine/lambda-express#20]
Probably something similar to https://github.com/jeremydaly/lambda-api#logging

**Comment by yokuze** [comment]
We decided that the standard log object will include these fields:

* level
* msg
* data

When the log level is `debug`, or something more verbose like `trace`, then these fields are also added:

* timer - the time, in milliseconds, since the start of the Lambda function request
* remaining - the time, in milliseconds, left until the Lambda function times out
* int - Interface. The type of Lambda event that triggered the request. One of `APIGW` or `ALB`

Here are some other fields we considered, but decided were not necessary or that we won't add at this time:

* time / id - not needed because they’re in the CloudWatch output
* function - not needed because each function (typically) has its own log stream
* memory - not needed because it’s logged in the execution report
* route / method - *come back to this later*
* sample - *we can revisit when we add sampling* (#26)

**Comment by yokuze** [comment]
This was added with https://github.com/silvermine/lambda-express/pull/27
